version: '3.5'
services:
  api1: # API - Instância 01
    image: gtmeira/rinha-backend-2023:1.0.0-SNAPSHOT
    hostname: api1
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.15GB'

  api2: # API - Instância 01
    image: gtmeira/rinha-backend-2023:1.0.0-SNAPSHOT
    hostname: api2
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.15GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.1GB'

  db: # Banco de dados
    image: postgres
    command: -c fsync=off -c synchronous_commit=off
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha1234
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '2.6GB'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rinha" ]
      interval: 5s
      timeout: 5s
      retries: 5